########## GLOBAL CONFIG ###########

global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
      monitor: 'global_monitoring'

#####################################

######### SWARM MONITORING ##########

scrape_configs:
  - job_name: 'swarm'
    scrape_interval: 10s
    static_configs:
         - targets: ['monitoring_cadvisor:8080','monitoring_node-exporter:9100']

# PROMETHEUS 

  - job_name: 'prometheus'
    scrape_interval: 25s
    static_configs:
         - targets: ['monitoring_prometheus:9090']
